### ISSUE TITLE
Provide some example(s) to get started

### ISSUE THREAD

**Issue by hbokh** [resnullius/deb-build-pkg#4]
Hi there,

Is this still working as it should, @ghostbar ?
I ask because I can't get `deb-build-pkg` do anything, not on Linux nor on macOS.
All I ever get when running with the `build` option is this:

```
# deb-build-pkg build
Will build version unstable for some-project on debian...
unstable: Pulling from resnullius/debian-devel
Digest: sha256:c2af3281872daddfef0438b097a671d09977d9e1ff6a289f4f1664c245ea7221
Status: Image is up to date for resnullius/debian-devel:unstable
docker.io/resnullius/debian-devel:unstable
/opt/workplace/some-project /opt/workplace
```

FYI I have a `debian/` dir inside `some-project` and using `run` instead of `build` will get me going on the prompt in Docker, but then I have to run the regular build commands by hand.

So could you please confirm this still works and if so, give a real world example in the `README.md`. TIA!

**UPDATE 1**
Probably something is missing in my `debian/` dir, because when I checkout `resnullius/capstone.deb`, and run `deb-build-pkg build` over there, it starts to do something more (but the build fails due to failing `orig.tar.gz` one dir up). 

**UPDATE 2**
Adding a URL to `debian/watch` started something. 🎉
However, the build failed due to the fact that the upstream tarball could not be found:
```
dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../some-project_3.1.1.orig.tar.{bz2,gz,lzma,xz}
```
On the local FS the `orig.tar.gz` is one dir up, but that's not added to the Docker container somehow.
The same error as for `resnullius/capstone.deb`.

**UPDATE 3**
Now experimenting with the right "filenamemangle" in `debina/watch`. A "v" is added for versioned released, I need to get that letter removed.

**Comment by ghostbar** [comment]
Hi!

https://github.com/resnullius/docker-deb-devel/blob/master/versions/x86_64/debian-unstable/scripts/entrypoint.sh#L68-L72

`deb-build-pkg` is basically a simple fast call for docker in order to use `docker-deb-devel` to do all the heavy lifting.

Indeed, the source package is not taken from your local FS but with `uscan`. That's the lines I just put in the URL.

It is weird capstone is no longer working. Its `debian/watch` must be out-of-date now.

And just so I answer your question explicitly: yes, it is still working as it should. :-)

**Comment by hbokh** [comment]
Thanks, Jose-Luis!
I see from current experience the crux is in the `debian/watch` indeed. 😉
I have a somewhat working "filenamemangle" to strip the letter "v" form the release:

```
opts="filenamemangle=s/(?:.*)?v?(\d[\d\.]*)\.tar\.gz/<project>-$1.tar.gz/" \
  https://github.com/<user>/<project>/tags (?:.*/)?v?(\d[\d\.]*)\.tar\.gz
```

but this needs to be fine-tuned.

PS. This is an awesome script / Docker image to use!

**Comment by ghostbar** [comment]
I'm happy someone else is using it!

Yes, `debian/watch` can give some pain. Capstone is not failing itself, it's just downloading a newer tarball than the version is packaged so it fails like "can't get 3.0.4" because of course, it downloaded 3.0.5. :-)

Hope you keep finding it useful :-)!!
